--Version 0.4 seed, copy into database terminal.

insert into "device" (create_at) values (current_timestamp);

/*Note that the accessors here are more complex than required
    due to using an excel tool to create these insert statements
    that requires unique accessors.
    In the planned admin console version of this, unique accessors will only be needed within a ux,
    or possibly accessors will be replaced with just the record id... Actually this is probably better...
*/
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','groupName','string',1);insert into record_attribute (attribute, "value","type","recordId") values ('name','Group','string',1);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',1);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','select','string',1);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','Select Group','string',1);insert into record_attribute (attribute, "value","type","recordId") values ('optionStore','groupOptions','string',1);insert into record_attribute (attribute, "value","type","recordId") values ('validation-required',TRUE,'boolean',1);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','id','string',2);insert into record_attribute (attribute, "value","type","recordId") values ('type','id','string',2);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','firstName','string',3);insert into record_attribute (attribute, "value","type","recordId") values ('name','First Name','string',3);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',3);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',3);insert into record_attribute (attribute, "value","type","recordId") values ('validation-required',TRUE,'boolean',3);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','lastName','string',4);insert into record_attribute (attribute, "value","type","recordId") values ('name','Last Name','string',4);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',4);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',4);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','dateOfBirth','string',5);insert into record_attribute (attribute, "value","type","recordId") values ('name','Date of Birth','string',5);insert into record_attribute (attribute, "value","type","recordId") values ('type','date','string',5);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','date','string',5);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','dateOFAmputation','string',6);insert into record_attribute (attribute, "value","type","recordId") values ('name','Amputation Date','string',6);insert into record_attribute (attribute, "value","type","recordId") values ('type','date','string',6);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','date','string',6);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','city','string',7);insert into record_attribute (attribute, "value","type","recordId") values ('name','City','string',7);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',7);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',7);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','country','string',8);insert into record_attribute (attribute, "value","type","recordId") values ('name','Country','string',8);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',8);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',8);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','gender','string',9);insert into record_attribute (attribute, "value","type","recordId") values ('name','Gender','string',9);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',9);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','radio','string',9);insert into record_attribute (attribute, "value","type","recordId") values ('validation-required',TRUE,'boolean',9);insert into record_attribute (attribute, "value","type","recordId") values ('option-0','Male','string',9);insert into record_attribute (attribute, "value","type","recordId") values ('option-1','Female','string',9);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','side','string',10);insert into record_attribute (attribute, "value","type","recordId") values ('name','Amputation Side','string',10);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',10);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','radio','string',10);insert into record_attribute (attribute, "value","type","recordId") values ('validation-required',TRUE,'boolean',10);insert into record_attribute (attribute, "value","type","recordId") values ('option-0','Left','string',10);insert into record_attribute (attribute, "value","type","recordId") values ('option-1','Right','string',10);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','amputationCause','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('name','Amputation Cause','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','select','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','Select Cause','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-0','Congenital','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-1','Diabetes','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-2','Traffic accident','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-3','Cancer','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-4','Burn','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-5','Frostbite','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-6','Industrial accident','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-7','Electrocution','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-8','Natural disaster','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-9','Infection','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-10','Conflict','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-11','Unknown','string',11);insert into record_attribute (attribute, "value","type","recordId") values ('option-12','Other','string',11);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','nozzleSize','string',12);insert into record_attribute (attribute, "value","type","recordId") values ('name','Nozzle Size','string',12);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',12);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','select','string',12);insert into record_attribute (attribute, "value","type","recordId") values ('default',TRUE,'boolean',12);insert into record_attribute (attribute, "value","type","recordId") values ('validation-required',TRUE,'boolean',12);insert into record_attribute (attribute, "value","type","recordId") values ('option-0','0.4mm','string',12);insert into record_attribute (attribute, "value","type","recordId") values ('option-1','0.6mm','string',12);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','amputationLevel','string',13);insert into record_attribute (attribute, "value","type","recordId") values ('name','Amputation Level','string',13);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',13);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','select','string',13);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','Select Level','string',13);insert into record_attribute (attribute, "value","type","recordId") values ('validation-required',TRUE,'boolean',13);insert into record_attribute (attribute, "value","type","recordId") values ('option-0','Transradial','string',13);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','l1','string',14);insert into record_attribute (attribute, "value","type","recordId") values ('name','L1','string',14);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',14);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',14);insert into record_attribute (attribute, "value","type","recordId") values ('step',1,'float',14);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure length.','string',14);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',14);insert into record_attribute (attribute, "value","type","recordId") values ('validation-min',18,'float',14);insert into record_attribute (attribute, "value","type","recordId") values ('validation-max',32,'float',14);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','l2','string',15);insert into record_attribute (attribute, "value","type","recordId") values ('name','L2','string',15);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',15);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',15);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure length.','string',15);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',15);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','l4','string',16);insert into record_attribute (attribute, "value","type","recordId") values ('name','L4','string',16);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',16);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',16);insert into record_attribute (attribute, "value","type","recordId") values ('step',0.5,'float',16);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure length.','string',16);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',16);insert into record_attribute (attribute, "value","type","recordId") values ('validation-min',14,'float',16);insert into record_attribute (attribute, "value","type","recordId") values ('validation-max',19,'float',16);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','c1','string',17);insert into record_attribute (attribute, "value","type","recordId") values ('name','C1','string',17);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',17);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',17);insert into record_attribute (attribute, "value","type","recordId") values ('step',0.5,'float',17);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure circumference.','string',17);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',17);insert into record_attribute (attribute, "value","type","recordId") values ('validation-min',14.5,'float',17);insert into record_attribute (attribute, "value","type","recordId") values ('validation-max',18,'float',17);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','c2','string',18);insert into record_attribute (attribute, "value","type","recordId") values ('name','C2','string',18);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',18);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',18);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure circumference.','string',18);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',18);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','c3','string',19);insert into record_attribute (attribute, "value","type","recordId") values ('name','C3','string',19);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',19);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',19);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure circumference.','string',19);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',19);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','c4','string',20);insert into record_attribute (attribute, "value","type","recordId") values ('name','C4','string',20);insert into record_attribute (attribute, "value","type","recordId") values ('type','float','string',20);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',20);insert into record_attribute (attribute, "value","type","recordId") values ('step',0.5,'float',20);insert into record_attribute (attribute, "value","type","recordId") values ('instruction','Measure circumference.','string',20);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','XX.X','string',20);insert into record_attribute (attribute, "value","type","recordId") values ('validation-min',20,'float',20);insert into record_attribute (attribute, "value","type","recordId") values ('validation-max',28,'float',20);

insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','patientDeviceName','string',21);insert into record_attribute (attribute, "value","type","recordId") values ('name','Device Name','string',21);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',21);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',21);insert into record_attribute (attribute, "value","type","recordId") values ('placeholder','Identifier for the Device','string',21);
insert into "record" (create_at) values (current_timestamp);insert into record_attribute (attribute, "value","type","recordId") values ('accessor','patientDeviceNotes','string',22);insert into record_attribute (attribute, "value","type","recordId") values ('name','Notes','string',22);insert into record_attribute (attribute, "value","type","recordId") values ('type','string','string',22);insert into record_attribute (attribute, "value","type","recordId") values ('inputType','text','string',22);



insert into "ux" ("accessor") values ('selectGroup');insert into ux_attribute (attribute, "value","type","uXId") values ('button','Select','string',1);insert into ux_attribute (attribute, "value","type","uXId") values ('preventDefault',TRUE,'boolean',1);insert into ux_record ("order", "recordId","uXId") values (0,1,1);
insert into "ux" ("accessor") values ('patientData');insert into ux_attribute (attribute, "value","type","uXId") values ('name','Patient','string',2);insert into ux_attribute (attribute, "value","type","uXId") values ('button','Save','string',2);insert into ux_attribute (attribute, "value","type","uXId") values ('preventDefault',TRUE,'boolean',2);insert into ux_record ("order", "recordId","uXId") values (0,3,2);insert into ux_record ("order", "recordId","uXId") values (1,4,2);insert into ux_record ("order", "recordId","uXId") values (2,5,2);insert into ux_record ("order", "recordId","uXId") values (3,6,2);insert into ux_record ("order", "recordId","uXId") values (4,7,2);insert into ux_record ("order", "recordId","uXId") values (5,8,2);insert into ux_record ("order", "recordId","uXId") values (6,9,2);insert into ux_record ("order", "recordId","uXId") values (7,11,2);
insert into "ux" ("accessor") values ('addDevice');insert into ux_attribute (attribute, "value","type","uXId") values ('name','Add Device','string',3);insert into ux_attribute (attribute, "value","type","uXId") values ('button','Add','string',3);insert into ux_attribute (attribute, "value","type","uXId") values ('preventDefault',TRUE,'boolean',3);insert into ux_record ("order", "recordId","uXId") values (0,10,3);insert into ux_record ("order", "recordId","uXId") values (1,12,3);insert into ux_record ("order", "recordId","uXId") values (2,13,3);
insert into "ux" ("accessor") values ('transradialDevice');insert into ux_attribute (attribute, "value","type","uXId") values ('name','Measurements','string',4);insert into ux_attribute (attribute, "value","type","uXId") values ('button','Save','string',4);insert into ux_attribute (attribute, "value","type","uXId") values ('preventDefault',TRUE,'boolean',4);
insert into ux_record ("order", "recordId","uXId") values (0,21,4);insert into ux_record ("order", "recordId","uXId") values (1,14,4);insert into ux_record ("order", "recordId","uXId") values (2,15,4);insert into ux_record ("order", "recordId","uXId") values (3,16,4);insert into ux_record ("order", "recordId","uXId") values (4,17,4);insert into ux_record ("order", "recordId","uXId") values (5,18,4);insert into ux_record ("order", "recordId","uXId") values (6,19,4);insert into ux_record ("order", "recordId","uXId") values (7,20,4);insert into ux_record ("order", "recordId","uXId") values (8,22,4);
insert into "ux" ("accessor") values ('patientCols');insert into ux_record ("order", "recordId","uXId") values (0,2,5);insert into ux_record ("order", "recordId","uXId") values (1,3,5);insert into ux_record ("order", "recordId","uXId") values (2,4,5);insert into ux_record ("order", "recordId","uXId") values (3,5,5);insert into ux_record ("order", "recordId","uXId") values (4,6,5);insert into ux_record ("order", "recordId","uXId") values (5,7,5);insert into ux_record ("order", "recordId","uXId") values (6,8,5);insert into ux_record ("order", "recordId","uXId") values (7,9,5);insert into ux_record ("order", "recordId","uXId") values (8,11,5);insert into ux_record ("order", "recordId","uXId") values (9,13,5);insert into ux_record ("order", "recordId","uXId") values (10,10,5);insert into ux_record ("order", "recordId","uXId") values (11,1,5);
insert into "ux" ("accessor") values ('deviceCols');insert into ux_attribute (attribute, "value","type","uXId") values ('name','Devices','string',6);
insert into ux_record ("order", "recordId","uXId") values (0,2,6);insert into ux_record ("order", "recordId","uXId") values (1,21,6);insert into ux_record ("order", "recordId","uXId") values (2,13,6);insert into ux_record ("order", "recordId","uXId") values (3,10,6);


--after initial user - seed the admin (confirm user id)
insert into "admin_access" ("isAdmin","userId") values (true, 1);



--TEST DATA
insert into ux_record ("order", "recordId","uXId") values (-1,12,3);
insert into ux_record ("order", "recordId","uXId") values (1,12,3);
insert into ux_record ("order", "recordId","uXId") values (-1,3,3);
insert into ux_record ("order", "recordId","uXId") values (1,3,3);
insert into ux_record ("order", "recordId","uXId") values (-1,3,3);

insert into "patient" (create_at) values (current_timestamp); --27
--device is 1 or 2

insert into patient_device ("patientId", "deviceId") values (27,1); --1

insert into patient_record ("patientId", "recordId", "value") values (27,3, 'John');
insert into patient_record ("patientId", "recordId", "value") values (27,4, 'Smite');
insert into patient_record ("patientId", "recordId", "value") values (27,4, 'Smith');
insert into patient_record ("patientId", "recordId", "value") values (27,5, current_timestamp);

insert into patient_device_record ("patientDeviceId", "recordId", "value") values (1,14, '27.4');
insert into patient_device_record ("patientDeviceId", "recordId", "value") values (1,15, '16.4');
insert into patient_device_record ("patientDeviceId", "recordId", "value") values (1,15, '17.4');

SELECT 'DROP VIEW ' || table_name || ';' 
FROM information_schema.views 
WHERE table_schema NOT IN ('pg_catalog', 'information_schema') 
AND table_name !~ '^pg_';

drop table migrations;
drop table typeorm_metadata;


drop table  admin_access        cascade;
drop table  "group"               cascade;
drop table  group_attribute     cascade;
drop table  measure             cascade;
drop table  measure_attribute   cascade;
drop table  migrations          cascade;
drop table  patient             cascade;
drop table  patient_attribute   cascade;
drop table  patient_group       cascade;
drop table  patient_measurement cascade;
drop table  site_auth           cascade;
drop table  typeorm_metadata    cascade;
drop table  "user"                cascade;
drop table  user_group          cascade;

 